name: build
on:
  push:
    branches:
      - develop
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g @hathora/cli
      - run: hathora-cloud deploy --appId app-2b09ca32-1259-44a0-bbd9-c19787c5a0c3 --token ${{ secrets.HATHORA_CLOUD_TOKEN }}
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install surge -g
      - run: npm install
        working-directory: shared
      - run: npm install
        working-directory: client
      - run: HATHORA_APP_ID=app-2b09ca32-1259-44a0-bbd9-c19787c5a0c3 npm run build
        working-directory: client
      - run: cp client/dist/index.html client/dist/200.html
      - run: surge client/dist hathora-multiplayer-gamejam.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
